# Configuration for application behavior and key bindings

# Commands to execute after logging in
after-login-command = []

# Commands to execute after startup
# This sets border colors and width for active and inactive windows
after-startup-command = []

# Enable starting the application at login
start-at-login = true

# Enable normalization features for container layouts
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Padding for accordion layout
accordion-padding = 15

# Default layout and orientation for root containers
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Commands triggered by monitor or focus changes
# Centers the mouse on the focused monitor or window
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = 'move-mouse window-lazy-center'

# Automatically unhide macOS hidden applications
automatically-unhide-macos-hidden-apps = false

# Key mapping configuration
[key-mapping]
preset = 'qwerty'

# Gap settings for window layouts
[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 8
outer.bottom = 8
outer.top = 8
outer.right = 8

# Environment variables for executed commands
[exec]
inherit-env-vars = true
[exec.env-vars]
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

# Main key bindings for common actions
[mode.main.binding]
alt-comma = 'layout accordion horizontal vertical'  # Change layout to accordion or horizontal/vertical
alt-slash = 'layout tiles horizontal vertical'  # Change layout to tiles or horizontal/vertical

alt-f = 'fullscreen'  # Toggle fullscreen mode

cmd-left = 'workspace --wrap-around prev'  # Switch to the previous workspace
cmd-right = 'workspace --wrap-around next'  # Switch to the next workspace
# cmd-shift-c = 'reload-config'  # Reload configuration file

# cmd-shift-f = 'layout floating tiling'  # Toggle between floating and tiling layouts


# ENTER MODES
cmd-shift-semicolon = 'mode service'  # Enter service mode
cmd-shift-r = 'mode resize'  # Enter resize mode

cmd-h = 'focus left'  # Move focus to the left
cmd-j = 'focus down'  # Move focus downward
cmd-k = 'focus up'  # Move focus upward
cmd-l = 'focus right'  # Move focus to the right

cmd-shift-h = 'move left'  # Move the window to the left
cmd-shift-j = 'move down'  # Move the window downward
cmd-shift-k = 'move up'  # Move the window upward
cmd-shift-l = 'move right'  # Move the window to the right

cmd-1 = 'workspace 1'  # Switch to workspace 1
cmd-2 = 'workspace 2'  # Switch to workspace 2
cmd-3 = 'workspace 3'  # Switch to workspace 3
cmd-4 = 'workspace 4'  # Switch to workspace 4
cmd-5 = 'workspace 5'  # Switch to workspace 5
cmd-6 = 'workspace 6'  # Switch to workspace 6
cmd-7 = 'workspace 7'  # Switch to workspace 7
cmd-8 = 'workspace 8'  # Switch to workspace 8
cmd-9 = 'workspace 9'  # Switch to workspace 9

cmd-ctrl-1 = 'move-node-to-workspace 1'  # Move the window to workspace 1
cmd-ctrl-2 = 'move-node-to-workspace 2'  # Move the window to workspace 2
cmd-ctrl-3 = 'move-node-to-workspace 3'  # Move the window to workspace 3
cmd-ctrl-4 = 'move-node-to-workspace 4'  # Move the window to workspace 4
cmd-ctrl-5 = 'move-node-to-workspace 5'  # Move the window to workspace 5
cmd-ctrl-6 = 'move-node-to-workspace 6'  # Move the window to workspace 6
cmd-ctrl-7 = 'move-node-to-workspace 7'  # Move the window to workspace 7
cmd-ctrl-8 = 'move-node-to-workspace 8'  # Move the window to workspace 8
cmd-ctrl-9 = 'move-node-to-workspace 9'  # Move the window to workspace 9
cmd-ctrl-0 = 'move-node-to-workspace 10'  # Move the window to workspace 10

cmd-ctrl-1 = ['move-node-to-workspace 1', 'workspace 1']  # Move and switch to workspace 1
cmd-ctrl-2 = ['move-node-to-workspace 2', 'workspace 2']  # Move and switch to workspace 2
cmd-ctrl-3 = ['move-node-to-workspace 3', 'workspace 3']  # Move and switch to workspace 3
cmd-ctrl-4 = ['move-node-to-workspace 4', 'workspace 4']  # Move and switch to workspace 4
cmd-ctrl-5 = ['move-node-to-workspace 5', 'workspace 5']  # Move and switch to workspace 5
cmd-ctrl-6 = ['move-node-to-workspace 6', 'workspace 6']  # Move and switch to workspace 6
cmd-ctrl-7 = ['move-node-to-workspace 7', 'workspace 7']  # Move and switch to workspace 7
cmd-ctrl-8 = ['move-node-to-workspace 8', 'workspace 8']  # Move and switch to workspace 8
cmd-ctrl-9 = ['move-node-to-workspace 9', 'workspace 9']  # Move and switch to workspace 9
cmd-ctrl-0 = ['move-node-to-workspace 10', 'workspace 10']  # Move and switch to workspace 10

cmd-shift-minus = "resize smart -50"
cmd-shift-equal = "resize smart +50"

alt-tab = 'workspace-back-and-forth'  # Switch to the last active workspace

# Manage mode bindings
[mode.service.binding]
esc = ['reload config', 'mode main']  # Exit service mode
enter = ['reload config', 'mode main']

c = ['reload-config', 'mode main']  # Reload configuration and exit service mode
r = ['flatten-workspace-tree', 'mode main']  # Flatten workspace hierarchy and exit service mode
f = ['layout floating tiling', 'mode main']  # Toggle layout and exit service mode
backspace = ['close-all-windows-but-current', 'mode main']  # Close all windows except the current one
cmd-shift-h = ['join-with left', 'mode main']  # Join container with the one on the left
cmd-shift-j = ['join-with down', 'mode main']  # Join container with the one below
cmd-shift-k = ['join-with up', 'mode main']  # Join container with the one above
cmd-shift-l = ['join-with right', 'mode main']  # Join container with the one on the right

# Resize mode bindings
[mode.resize.binding]
esc = 'mode main'  # Exit resize mode
enter = 'mode main'  # Exit resize mode

h = 'resize width -50'  # Decrease width by 50 units
j = 'resize height +50'  # Increase height by 50 units
k = 'resize height -50'  # Decrease height by 50 units
l = 'resize width +50'  # Increase width by 50 units
